### PR TITLE
Add wl_resource_get_client to lib

### PR DESCRIPTION
**Pull request by m-col**
I used this for https://github.com/qtile/qtile/pull/3663

Is there a more appropriate way to get access to this function, considering it isn't used by pywayland directly, or is this fine?

### CODE REVIEW

**Comment by flacjacket** [comment]
I'm fine with this. Is this something that we could wrap in a `pywayland.server.Client` and use something like `wlroots.Ptr` to compare this to the `other` client? We'd need to come up with a way to create a `Client` without it being created. If that makes things too hard, we can stick with this to get the functionality in and fix it up as we find better ways to structure this.

**Comment by m-col** [comment]
Something equivalent to this (though the construction could be moved to `__init__` if we make its current arguments and creation optional)?:
```py
    @classmethod
    def from_resource(cls, resource: Resource) -> Client:
        """Look up the corresponding wl_client for a wl_resource

        :param resource: The wl_resource
        :type resource: pywayland.protocol_core.Resource
        :returns:
            A `Client` instance.
        """
        client = Client.__new__()
        client._ptr = lib.wl_resource_get_client(res_ptr)
        client._display = None
        return client

```
That would be nice. Currently `Client.__init__` _creates_ a new wl_client, rather than allowing for representation of existing wl_clients, but that would be useful for cases like this.

**Comment by flacjacket** [comment]
Right, something like that!

**Comment by m-col** [comment]
Commit message for info on the updates:
```
This provides 2 alternative ways to construct Client instances:

- via the `from_resource` class method, from a wl_resource pointer. This
  accepts a pointer cdata rather than a `Resource` instance, as should
  be feasible to use this method without requiring an interface to
  implement the `Resource` generic for it. E.g. the layer shell protocol
  doesn't have a `Resource` class and this is fine; the requirement
  would disable usage of `Client.from_resource` from layer shell
  components.
- by passing `ptr=` to `Client` directly to represent an existing
  wl_client rather than creating a fresh one.
```

**Comment by m-col** [comment]
This is causing an interesting mypy error:
```
pywayland/server/client.py:157: error: Module has no attribute "wl_resource_get_client"; maybe "wl_resource_get_id", "wl_resource_get_version", or "wl_resource_get_user_data"?  [attr-defined]
```

The new C function added to the ffi lib isn't found by mypy so mypy is complaining about the absent attr. Any ideas how this can be resolved? Not sure I've seen this before with all of the ffi modules we use!

**Comment by flacjacket** [comment]
Right, you can add the stubs to `pywayland/_ffi/lib.pyi`.

**Review by flacjacket — APPROVED** [review]
Great!

**Pull request merged**
