### PR TITLE
Expose wl_display_flush_clients as server Display method

### PR DESCRIPTION
**Pull request by m-col**
OK making this change was much easier than I expected :D 

https://github.com/flacjacket/pywayland/issues/19

### CODE REVIEW

**Comment by flacjacket** [comment]
Thanks for this, you beat my change in #21 by just a minute!

Would it help to have a new version tagged with the update?

**Comment by m-col** [comment]
Yes that would be great, thanks!

**Comment by flacjacket** [comment]
Done! 0.4 tagged and pushed.

**Comment by m-col** [comment]
Yes that would be great, thanks!

**Pull request merged**
